version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env  
    networks:
      - backend

  streamlit:
    build: ./streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - backend
    entrypoint: ["./wait-for-it.sh", "fastapi:8000", "--", "streamlit", "run", "streamlit_app.py"]

networks:
  backend:
    driver: bridge
