version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./app:/app

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: streamlit_service
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_API_URL=http://app:8000
    volumes:
      - ./streamlit:/app
    depends_on:
      - app